version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn clean install
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Save jar
          command: |
            mv "./change-log-generator-base/target/changelog-generator-jar-with-dependencies.jar" ~/artifacts
          when: always
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - persist_to_workspace:
          root: .
          paths: .
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/artifacts
      - store_artifacts:
          path: ~/junit
      - run:
          name: Send to CodeCov
          command: bash <(curl -s https://codecov.io/bash)
  release:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - attach_workspace:
          at: ~/repo
      - run: mvn clean install
      - run:
          name: Release
          command: |
            mvn -pl change-log-generator-gui changelog:s3-release
          when: always
workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/



